server:
  port: 9008

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties/
  application:
    name: config-server
  profiles:
    active: native
